package com.elixir.loader;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class attr {
        public static final int action = 0x7f010000;
        public static final int activityAction = 0x7f010001;
        public static final int activityName = 0x7f010002;
        public static final int alpha = 0x7f010003;
        public static final int alwaysExpand = 0x7f010004;
        public static final int animationBackgroundColor = 0x7f010005;
        public static final int argType = 0x7f010006;
        public static final int clearTop = 0x7f010007;
        public static final int data = 0x7f010008;
        public static final int dataPattern = 0x7f010009;
        public static final int destination = 0x7f01000a;
        public static final int dragRangeMaxRatio = 0x7f01000b;
        public static final int dragRangeMinRatio = 0x7f01000c;
        public static final int embeddingDividerColor = 0x7f01000d;
        public static final int embeddingDividerType = 0x7f01000e;
        public static final int embeddingDividerWidthDp = 0x7f01000f;
        public static final int enterAnim = 0x7f010010;
        public static final int exitAnim = 0x7f010011;
        public static final int finishPrimaryWithPlaceholder = 0x7f010012;
        public static final int finishPrimaryWithSecondary = 0x7f010013;
        public static final int finishSecondaryWithPrimary = 0x7f010014;
        public static final int font = 0x7f010015;
        public static final int fontProviderAuthority = 0x7f010016;
        public static final int fontProviderCerts = 0x7f010017;
        public static final int fontProviderFallbackQuery = 0x7f010018;
        public static final int fontProviderFetchStrategy = 0x7f010019;
        public static final int fontProviderFetchTimeout = 0x7f01001a;
        public static final int fontProviderPackage = 0x7f01001b;
        public static final int fontProviderQuery = 0x7f01001c;
        public static final int fontProviderSystemFontFamily = 0x7f01001d;
        public static final int fontStyle = 0x7f01001e;
        public static final int fontVariationSettings = 0x7f01001f;
        public static final int fontWeight = 0x7f010020;
        public static final int graph = 0x7f010021;
        public static final int isDraggingToFullscreenAllowed = 0x7f010022;
        public static final int lStar = 0x7f010023;
        public static final int launchSingleTop = 0x7f010024;
        public static final int mimeType = 0x7f010025;
        public static final int navGraph = 0x7f010026;
        public static final int nestedScrollViewStyle = 0x7f010027;
        public static final int nullable = 0x7f010028;
        public static final int placeholderActivityName = 0x7f010029;
        public static final int popEnterAnim = 0x7f01002a;
        public static final int popExitAnim = 0x7f01002b;
        public static final int popUpTo = 0x7f01002c;
        public static final int popUpToInclusive = 0x7f01002d;
        public static final int popUpToSaveState = 0x7f01002e;
        public static final int postSplashScreenTheme = 0x7f01002f;
        public static final int primaryActivityName = 0x7f010030;
        public static final int queryPatterns = 0x7f010031;
        public static final int restoreState = 0x7f010032;
        public static final int route = 0x7f010033;
        public static final int secondaryActivityAction = 0x7f010034;
        public static final int secondaryActivityName = 0x7f010035;
        public static final int shortcutMatchRequired = 0x7f010036;
        public static final int splashScreenIconSize = 0x7f010037;
        public static final int splitChangeAnimation = 0x7f010038;
        public static final int splitCloseAnimation = 0x7f010039;
        public static final int splitLayoutDirection = 0x7f01003a;
        public static final int splitMaxAspectRatioInLandscape = 0x7f01003b;
        public static final int splitMaxAspectRatioInPortrait = 0x7f01003c;
        public static final int splitMinHeightDp = 0x7f01003d;
        public static final int splitMinSmallestWidthDp = 0x7f01003e;
        public static final int splitMinWidthDp = 0x7f01003f;
        public static final int splitOpenAnimation = 0x7f010040;
        public static final int splitRatio = 0x7f010041;
        public static final int startDestination = 0x7f010042;
        public static final int stickyPlaceholder = 0x7f010043;
        public static final int tag = 0x7f010044;
        public static final int targetPackage = 0x7f010045;
        public static final int ttcIndex = 0x7f010046;
        public static final int uri = 0x7f010047;
        public static final int windowSplashScreenAnimatedIcon = 0x7f010048;
        public static final int windowSplashScreenAnimationDuration = 0x7f010049;
        public static final int windowSplashScreenBackground = 0x7f01004a;
        public static final int windowSplashScreenIconBackgroundColor = 0x7f01004b;
    }

    public static final class color {
        public static final int ic_launcher_background = 0x7f020005;
        public static final int splash_background = 0x7f02000b;
        public static final int splash_icon_background = 0x7f02000c;
    }

    public static final class dimen {
        public static final int splashscreen_icon_mask_size_no_background = 0x7f030016;
        public static final int splashscreen_icon_mask_stroke_no_background = 0x7f030018;
        public static final int splashscreen_icon_size_no_background = 0x7f03001b;
    }

    public static final class drawable {
        public static final int compat_splash_screen_no_icon_background = 0x7f040001;
        public static final int ic_launcher_foreground = 0x7f040009;
        public static final int ic_splash = 0x7f04000a;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f050000;
        public static final int accessibility_custom_action_0 = 0x7f050001;
        public static final int accessibility_custom_action_1 = 0x7f050002;
        public static final int accessibility_custom_action_10 = 0x7f050003;
        public static final int accessibility_custom_action_11 = 0x7f050004;
        public static final int accessibility_custom_action_12 = 0x7f050005;
        public static final int accessibility_custom_action_13 = 0x7f050006;
        public static final int accessibility_custom_action_14 = 0x7f050007;
        public static final int accessibility_custom_action_15 = 0x7f050008;
        public static final int accessibility_custom_action_16 = 0x7f050009;
        public static final int accessibility_custom_action_17 = 0x7f05000a;
        public static final int accessibility_custom_action_18 = 0x7f05000b;
        public static final int accessibility_custom_action_19 = 0x7f05000c;
        public static final int accessibility_custom_action_2 = 0x7f05000d;
        public static final int accessibility_custom_action_20 = 0x7f05000e;
        public static final int accessibility_custom_action_21 = 0x7f05000f;
        public static final int accessibility_custom_action_22 = 0x7f050010;
        public static final int accessibility_custom_action_23 = 0x7f050011;
        public static final int accessibility_custom_action_24 = 0x7f050012;
        public static final int accessibility_custom_action_25 = 0x7f050013;
        public static final int accessibility_custom_action_26 = 0x7f050014;
        public static final int accessibility_custom_action_27 = 0x7f050015;
        public static final int accessibility_custom_action_28 = 0x7f050016;
        public static final int accessibility_custom_action_29 = 0x7f050017;
        public static final int accessibility_custom_action_3 = 0x7f050018;
        public static final int accessibility_custom_action_30 = 0x7f050019;
        public static final int accessibility_custom_action_31 = 0x7f05001a;
        public static final int accessibility_custom_action_4 = 0x7f05001b;
        public static final int accessibility_custom_action_5 = 0x7f05001c;
        public static final int accessibility_custom_action_6 = 0x7f05001d;
        public static final int accessibility_custom_action_7 = 0x7f05001e;
        public static final int accessibility_custom_action_8 = 0x7f05001f;
        public static final int accessibility_custom_action_9 = 0x7f050020;
        public static final int action_container = 0x7f050021;
        public static final int action_divider = 0x7f050022;
        public static final int action_image = 0x7f050023;
        public static final int action_text = 0x7f050024;
        public static final int actions = 0x7f050025;
        public static final int adjacent = 0x7f050026;
        public static final int always = 0x7f050027;
        public static final int alwaysAllow = 0x7f050028;
        public static final int alwaysDisallow = 0x7f050029;
        public static final int androidx_compose_ui_view_composition_context = 0x7f05002a;
        public static final int androidx_window_activity_scope = 0x7f05002b;
        public static final int async = 0x7f05002c;
        public static final int auto_clear_focus_behavior_tag = 0x7f05002d;
        public static final int blocking = 0x7f05002e;
        public static final int bottomToTop = 0x7f05002f;
        public static final int chronometer = 0x7f050030;
        public static final int compose_prefetch_scheduler = 0x7f050031;
        public static final int compose_view_saveable_id_tag = 0x7f050032;
        public static final int consume_window_insets_tag = 0x7f050033;
        public static final int dialog_button = 0x7f050034;
        public static final int draggable = 0x7f050035;
        public static final int edit_text_id = 0x7f050036;
        public static final int fixed = 0x7f050037;
        public static final int forever = 0x7f050038;
        public static final int ghost_view = 0x7f050039;
        public static final int ghost_view_holder = 0x7f05003a;
        public static final int hide_graphics_layer_in_inspector_tag = 0x7f05003b;
        public static final int hide_ime_id = 0x7f05003c;
        public static final int hide_in_inspector_tag = 0x7f05003d;
        public static final int icon = 0x7f05003e;
        public static final int icon_group = 0x7f05003f;
        public static final int info = 0x7f050040;
        public static final int inspection_slot_table_set = 0x7f050041;
        public static final int is_pooling_container_tag = 0x7f050042;
        public static final int italic = 0x7f050043;
        public static final int jumpCut = 0x7f050044;
        public static final int line1 = 0x7f050045;
        public static final int line3 = 0x7f050046;
        public static final int locale = 0x7f050047;
        public static final int ltr = 0x7f050048;
        public static final int nav_controller_view_tag = 0x7f050049;
        public static final int never = 0x7f05004a;
        public static final int normal = 0x7f05004b;
        public static final int notification_background = 0x7f05004c;
        public static final int notification_main_column = 0x7f05004d;
        public static final int notification_main_column_container = 0x7f05004e;
        public static final int parent_matrix = 0x7f05004f;
        public static final int pooling_container_listener_holder_tag = 0x7f050050;
        public static final int report_drawn = 0x7f050051;
        public static final int right_icon = 0x7f050052;
        public static final int right_side = 0x7f050053;
        public static final int rtl = 0x7f050054;
        public static final int save_non_transition_alpha = 0x7f050055;
        public static final int save_overlay_view = 0x7f050056;
        public static final int splashscreen_icon_view = 0x7f050057;
        public static final int systemDefault = 0x7f050058;
        public static final int tag_accessibility_actions = 0x7f050059;
        public static final int tag_accessibility_clickable_spans = 0x7f05005a;
        public static final int tag_accessibility_heading = 0x7f05005b;
        public static final int tag_accessibility_pane_title = 0x7f05005c;
        public static final int tag_compat_insets_dispatch = 0x7f05005d;
        public static final int tag_on_apply_window_listener = 0x7f05005e;
        public static final int tag_on_receive_content_listener = 0x7f05005f;
        public static final int tag_on_receive_content_mime_types = 0x7f050060;
        public static final int tag_screen_reader_focusable = 0x7f050061;
        public static final int tag_state_description = 0x7f050062;
        public static final int tag_system_bar_state_monitor = 0x7f050063;
        public static final int tag_transition_group = 0x7f050064;
        public static final int tag_unhandled_key_event_manager = 0x7f050065;
        public static final int tag_unhandled_key_listeners = 0x7f050066;
        public static final int tag_window_insets_animation_callback = 0x7f050067;
        public static final int text = 0x7f050068;
        public static final int text2 = 0x7f050069;
        public static final int time = 0x7f05006a;
        public static final int title = 0x7f05006b;
        public static final int topToBottom = 0x7f05006c;
        public static final int transition_clip = 0x7f05006d;
        public static final int transition_current_scene = 0x7f05006e;
        public static final int transition_image_transform = 0x7f05006f;
        public static final int transition_layout_save = 0x7f050070;
        public static final int transition_pause_alpha = 0x7f050071;
        public static final int transition_position = 0x7f050072;
        public static final int transition_scene_layoutid_cache = 0x7f050073;
        public static final int transition_transform = 0x7f050074;
        public static final int view_tree_disjoint_parent = 0x7f050075;
        public static final int view_tree_lifecycle_owner = 0x7f050076;
        public static final int view_tree_navigation_event_dispatcher_owner = 0x7f050077;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f050078;
        public static final int view_tree_saved_state_registry_owner = 0x7f050079;
        public static final int view_tree_view_model_store_owner = 0x7f05007a;
        public static final int wrapped_composition_tag = 0x7f05007b;
    }

    public static final class integer {
        public static final int default_icon_animation_duration = 0x7f060000;
        public static final int m3c_window_layout_in_display_cutout_mode = 0x7f060001;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f080000;
        public static final int ic_launcher_round = 0x7f080001;
    }

    public static final class string {
        public static final int androidx_startup = 0x7f090002;
        public static final int app_name = 0x7f090003;
        public static final int close_drawer = 0x7f09000b;
        public static final int close_sheet = 0x7f09000c;
        public static final int default_error_message = 0x7f09000d;
        public static final int default_popup_window_title = 0x7f09000e;
        public static final int in_progress = 0x7f090010;
        public static final int indeterminate = 0x7f090011;
        public static final int m3c_bottom_sheet_collapse_description = 0x7f090022;
        public static final int m3c_bottom_sheet_dismiss_description = 0x7f090023;
        public static final int m3c_bottom_sheet_drag_handle_description = 0x7f090024;
        public static final int m3c_bottom_sheet_expand_description = 0x7f090025;
        public static final int m3c_bottom_sheet_pane_title = 0x7f090026;
        public static final int m3c_dialog = 0x7f090047;
        public static final int m3c_dropdown_menu_collapsed = 0x7f090048;
        public static final int m3c_dropdown_menu_expanded = 0x7f090049;
        public static final int m3c_dropdown_menu_toggle = 0x7f09004a;
        public static final int m3c_snackbar_pane_title = 0x7f090050;
        public static final int navigation_menu = 0x7f090069;
        public static final int not_selected = 0x7f09006a;
        public static final int selected = 0x7f09006d;
        public static final int state_empty = 0x7f09006f;
        public static final int state_off = 0x7f090070;
        public static final int state_on = 0x7f090071;
        public static final int switch_role = 0x7f090073;
        public static final int tab = 0x7f090074;
        public static final int template_percent = 0x7f090075;
        public static final int tooltip_description = 0x7f090076;
        public static final int tooltip_label = 0x7f090077;
    }

    public static final class style {
        public static final int Base_Theme_SplashScreen = 0x7f0a0000;
        public static final int Base_Theme_SplashScreen_DayNight = 0x7f0a0001;
        public static final int Base_Theme_SplashScreen_Light = 0x7f0a0002;
        public static final int DialogWindowTheme = 0x7f0a0007;
        public static final int EdgeToEdgeFloatingDialogTheme = 0x7f0a0008;
        public static final int EdgeToEdgeFloatingDialogWindowTheme = 0x7f0a0009;
        public static final int FloatingDialogWindowTheme = 0x7f0a000a;
        public static final int Theme_ElixirLoader = 0x7f0a0010;
        public static final int Theme_ElixirLoader_Splash = 0x7f0a0011;
        public static final int Theme_SplashScreen = 0x7f0a0012;
        public static final int Theme_SplashScreen_Common = 0x7f0a0013;
    }

    public static final class xml {
        public static final int backup_rules = 0x7f0c0000;
        public static final int data_extraction_rules = 0x7f0c0001;
        public static final int file_paths = 0x7f0c0002;
    }
}
