package defpackage;

/* compiled from: r8-map-id-09617c094fd1d5b705d683180bfdcc3cc35b0c5e13ee7f309dceccc0900ba8d2 */
/* loaded from: classes.dex */
public abstract class hc2 {
    public static final long A;
    public static final long A0;
    public static final jf0 A1;
    public static final long B;
    public static final sd0 B0;
    public static final long B1;
    public static final long C;
    public static final jf0 C0;
    public static final long C1;
    public static final sd0 D;
    public static final long D0;
    public static final long D1;
    public static final jf0 E;
    public static final long E0;
    public static final sd0 E1;
    public static final long F;
    public static final long F0;
    public static final jf0 F1;
    public static final long G;
    public static final sd0 G0;
    public static final long G1;
    public static final long H;
    public static final jf0 H0;
    public static final long H1;
    public static final sd0 I;
    public static final long I0;
    public static final long I1;
    public static final jf0 J;
    public static final long J0;
    public static final sd0 J1;
    public static final long K;
    public static final long K0;
    public static final jf0 K1;
    public static final long L;
    public static final sd0 L0;
    public static final long L1;
    public static final long M;
    public static final jf0 M0;
    public static final long M1;
    public static final sd0 N;
    public static final long N0;
    public static final long N1;
    public static final jf0 O;
    public static final long O0;
    public static final sd0 O1;
    public static final long P;
    public static final long P0;
    public static final jf0 P1;
    public static final long Q;
    public static final sd0 Q0;
    public static final long Q1;
    public static final long R;
    public static final jf0 R0;
    public static final long R1;
    public static final sd0 S;
    public static final long S0;
    public static final long S1;
    public static final jf0 T;
    public static final long T0;
    public static final sd0 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final sd0 V0;
    public static final long W;
    public static final jf0 W0;
    public static final sd0 X;
    public static final long X0;
    public static final jf0 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final jf0 a;
    public static final long a0;
    public static final sd0 a1;
    public static final long b;
    public static final long b0;
    public static final jf0 b1;
    public static final long c;
    public static final sd0 c0;
    public static final long c1;
    public static final long d;
    public static final jf0 d0;
    public static final long d1;
    public static final sd0 e;
    public static final long e0;
    public static final long e1;
    public static final jf0 f;
    public static final long f0;
    public static final sd0 f1;
    public static final long g;
    public static final long g0;
    public static final jf0 g1;
    public static final long h;
    public static final sd0 h0;
    public static final long h1;
    public static final long i;
    public static final jf0 i0;
    public static final long i1;
    public static final sd0 j;
    public static final long j0;
    public static final long j1;
    public static final jf0 k;
    public static final long k0;
    public static final sd0 k1;
    public static final long l;
    public static final long l0;
    public static final jf0 l1;
    public static final long m;
    public static final sd0 m0;
    public static final long m1;
    public static final long n;
    public static final jf0 n0;
    public static final long n1;
    public static final sd0 o;
    public static final long o0;
    public static final long o1;
    public static final jf0 p;
    public static final long p0;
    public static final sd0 p1;
    public static final long q;
    public static final long q0;
    public static final jf0 q1;
    public static final long r;
    public static final sd0 r0;
    public static final long r1;
    public static final long s;
    public static final jf0 s0;
    public static final long s1;
    public static final sd0 t;
    public static final long t0;
    public static final long t1;
    public static final jf0 u;
    public static final long u0;
    public static final sd0 u1;
    public static final long v;
    public static final long v0;
    public static final jf0 v1;
    public static final long w;
    public static final sd0 w0;
    public static final long w1;
    public static final long x;
    public static final jf0 x0;
    public static final long x1;
    public static final sd0 y;
    public static final long y0;
    public static final long y1;
    public static final jf0 z;
    public static final long z0;
    public static final sd0 z1;

    static {
        sd0 sd0Var = oc2.a;
        jf0 jf0Var = g52.b;
        a = jf0Var;
        b = pp1.r(24.0d);
        c = pp1.s(16);
        d = pp1.r(0.5d);
        sd0 sd0Var2 = oc2.c;
        e = sd0Var2;
        f = jf0Var;
        g = pp1.r(20.0d);
        h = pp1.s(14);
        i = pp1.r(0.2d);
        j = sd0Var2;
        k = jf0Var;
        l = pp1.r(16.0d);
        m = pp1.s(12);
        n = pp1.r(0.4d);
        o = sd0Var2;
        p = jf0Var;
        q = pp1.r(64.0d);
        r = pp1.s(57);
        long r2 = pp1.r(0.2d);
        o92[] o92VarArr = n92.b;
        long j2 = r2 & 1095216660480L;
        if (j2 == 0) {
            ml0.a("Cannot perform operation for Unspecified type.");
        }
        s = pp1.C(j2, -n92.c(r2));
        t = sd0Var2;
        u = jf0Var;
        v = pp1.r(52.0d);
        w = pp1.s(45);
        x = pp1.r(0.0d);
        y = sd0Var2;
        z = jf0Var;
        A = pp1.r(44.0d);
        B = pp1.s(36);
        C = pp1.r(0.0d);
        D = sd0Var2;
        E = jf0Var;
        F = pp1.r(40.0d);
        G = pp1.s(32);
        H = pp1.r(0.0d);
        I = sd0Var2;
        J = jf0Var;
        K = pp1.r(36.0d);
        L = pp1.s(28);
        M = pp1.r(0.0d);
        N = sd0Var2;
        O = jf0Var;
        P = pp1.r(32.0d);
        Q = pp1.s(24);
        R = pp1.r(0.0d);
        S = sd0Var2;
        T = jf0Var;
        U = pp1.r(20.0d);
        V = pp1.s(14);
        W = pp1.r(0.1d);
        sd0 sd0Var3 = oc2.b;
        X = sd0Var3;
        Y = jf0Var;
        Z = pp1.r(16.0d);
        a0 = pp1.s(12);
        b0 = pp1.r(0.5d);
        c0 = sd0Var3;
        d0 = jf0Var;
        e0 = pp1.r(16.0d);
        f0 = pp1.s(11);
        g0 = pp1.r(0.5d);
        h0 = sd0Var3;
        i0 = jf0Var;
        j0 = pp1.r(28.0d);
        k0 = pp1.s(22);
        l0 = pp1.r(0.0d);
        m0 = sd0Var2;
        n0 = jf0Var;
        o0 = pp1.r(24.0d);
        p0 = pp1.s(16);
        q0 = pp1.r(0.2d);
        r0 = sd0Var3;
        s0 = jf0Var;
        t0 = pp1.r(20.0d);
        u0 = pp1.s(14);
        v0 = pp1.r(0.1d);
        w0 = sd0Var3;
        x0 = jf0Var;
        y0 = pp1.r(24.0d);
        z0 = pp1.s(16);
        A0 = pp1.r(0.15d);
        B0 = sd0Var3;
        C0 = jf0Var;
        D0 = pp1.r(20.0d);
        E0 = pp1.s(14);
        F0 = pp1.r(0.25d);
        G0 = sd0Var3;
        H0 = jf0Var;
        I0 = pp1.r(16.0d);
        J0 = pp1.s(12);
        K0 = pp1.r(0.4d);
        L0 = sd0Var3;
        M0 = jf0Var;
        N0 = pp1.r(64.0d);
        O0 = pp1.s(57);
        P0 = pp1.s(0);
        Q0 = sd0Var3;
        R0 = jf0Var;
        S0 = pp1.r(52.0d);
        T0 = pp1.s(45);
        U0 = pp1.s(0);
        V0 = sd0Var3;
        W0 = jf0Var;
        X0 = pp1.r(44.0d);
        Y0 = pp1.s(36);
        Z0 = pp1.s(0);
        a1 = sd0Var3;
        b1 = jf0Var;
        c1 = pp1.r(40.0d);
        d1 = pp1.s(32);
        e1 = pp1.s(0);
        f1 = sd0Var3;
        g1 = jf0Var;
        h1 = pp1.r(36.0d);
        i1 = pp1.s(28);
        j1 = pp1.s(0);
        k1 = sd0Var3;
        l1 = jf0Var;
        m1 = pp1.r(32.0d);
        n1 = pp1.s(24);
        o1 = pp1.s(0);
        p1 = sd0Var3;
        q1 = jf0Var;
        r1 = pp1.r(20.0d);
        s1 = pp1.s(14);
        t1 = pp1.r(0.1d);
        sd0 sd0Var4 = oc2.a;
        u1 = sd0Var4;
        v1 = jf0Var;
        w1 = pp1.r(16.0d);
        x1 = pp1.s(12);
        y1 = pp1.r(0.5d);
        z1 = sd0Var4;
        A1 = jf0Var;
        B1 = pp1.r(16.0d);
        C1 = pp1.s(11);
        D1 = pp1.r(0.5d);
        E1 = sd0Var4;
        F1 = jf0Var;
        G1 = pp1.r(28.0d);
        H1 = pp1.s(22);
        I1 = pp1.s(0);
        J1 = sd0Var3;
        K1 = jf0Var;
        L1 = pp1.r(24.0d);
        M1 = pp1.s(16);
        N1 = pp1.r(0.15d);
        O1 = sd0Var4;
        P1 = jf0Var;
        Q1 = pp1.r(20.0d);
        R1 = pp1.s(14);
        S1 = pp1.r(0.1d);
        T1 = sd0Var4;
    }
}
