package defpackage;

/* compiled from: r8-map-id-09617c094fd1d5b705d683180bfdcc3cc35b0c5e13ee7f309dceccc0900ba8d2 */
/* loaded from: classes.dex */
public abstract class ho {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = yd1.x;
        a = j2;
        b = yd1.e;
        c = yd1.g;
        d = yd1.v;
        long j3 = yd1.I;
        e = j3;
        f = yd1.m;
        long j4 = yd1.i;
        g = j4;
        h = yd1.b;
        i = yd1.a;
        j = yd1.E;
        long j5 = yd1.D;
        k = j5;
        l = j5;
        m = yd1.G;
        n = yd1.L;
        long j6 = yd1.K;
        o = j6;
        p = j6;
        q = yd1.N;
        r = j4;
        s = yd1.y;
        t = yd1.S;
        long j7 = yd1.R;
        u = j7;
        v = j7;
        w = yd1.U;
        x = yd1.z;
        y = yd1.B;
        z = yd1.H;
        long j8 = yd1.J;
        A = j8;
        B = j8;
        C = j3;
        D = yd1.h;
        E = yd1.O;
        long j9 = yd1.Q;
        F = j9;
        G = j9;
        H = yd1.P;
        I = j2;
        J = j2;
        K = yd1.u;
        L = yd1.t;
        M = yd1.s;
        N = yd1.w;
        O = yd1.j;
        P = yd1.r;
        Q = yd1.C;
        R = yd1.V;
        long j10 = yd1.X;
        S = j10;
        T = j10;
        U = yd1.W;
    }
}
