package defpackage;

/* compiled from: r8-map-id-09617c094fd1d5b705d683180bfdcc3cc35b0c5e13ee7f309dceccc0900ba8d2 */
/* loaded from: classes.dex */
public final class mo {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public rk W;
    public rk X;
    public rk Y;
    public wl Z;
    public final long a;
    public ua2 a0;
    public final long b;
    public yi0 b0;
    public final long c;
    public yi0 c0;
    public final long d;
    public xv0 d0;
    public final long e;
    public s01 e0;
    public final long f;
    public my1 f0;
    public final long g;
    public x42 g0;
    public final long h;
    public c72 h0;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public mo(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        l90.u(this.a, sb, "onPrimary=");
        l90.u(this.b, sb, "primaryContainer=");
        l90.u(this.c, sb, "onPrimaryContainer=");
        long j = this.d;
        l90.u(j, sb, "inversePrimary=");
        l90.u(this.e, sb, "secondary=");
        l90.u(this.f, sb, "onSecondary=");
        l90.u(this.g, sb, "secondaryContainer=");
        l90.u(this.h, sb, "onSecondaryContainer=");
        l90.u(this.i, sb, "tertiary=");
        l90.u(this.j, sb, "onTertiary=");
        l90.u(this.k, sb, "tertiaryContainer=");
        l90.u(this.l, sb, "onTertiaryContainer=");
        l90.u(this.m, sb, "background=");
        l90.u(this.n, sb, "onBackground=");
        l90.u(this.o, sb, "surface=");
        l90.u(this.p, sb, "onSurface=");
        l90.u(this.q, sb, "surfaceVariant=");
        l90.u(this.r, sb, "onSurfaceVariant=");
        l90.u(this.s, sb, "surfaceTint=");
        l90.u(this.t, sb, "inverseSurface=");
        l90.u(this.u, sb, "inverseOnSurface=");
        l90.u(this.v, sb, "error=");
        l90.u(this.w, sb, "onError=");
        l90.u(this.x, sb, "errorContainer=");
        l90.u(this.y, sb, "onErrorContainer=");
        l90.u(this.z, sb, "outline=");
        l90.u(this.A, sb, "outlineVariant=");
        l90.u(this.B, sb, "scrim=");
        l90.u(this.C, sb, "surfaceBright=");
        l90.u(this.D, sb, "surfaceDim=");
        l90.u(this.E, sb, "surfaceContainer=");
        l90.u(this.F, sb, "surfaceContainerHigh=");
        l90.u(this.G, sb, "surfaceContainerHighest=");
        l90.u(this.H, sb, "surfaceContainerLow=");
        l90.u(this.I, sb, "surfaceContainerLowest=");
        l90.u(this.J, sb, "primaryFixed=");
        l90.u(this.K, sb, "primaryFixedDim=");
        l90.u(this.L, sb, "onPrimaryFixed=");
        l90.u(j, sb, "onPrimaryFixedVariant=");
        l90.u(this.N, sb, "secondaryFixed=");
        l90.u(this.O, sb, "secondaryFixedDim=");
        l90.u(this.P, sb, "onSecondaryFixed=");
        l90.u(this.Q, sb, "onSecondaryFixedVariant=");
        l90.u(this.R, sb, "tertiaryFixed=");
        l90.u(this.S, sb, "tertiaryFixedDim=");
        l90.u(this.T, sb, "onTertiaryFixed=");
        l90.u(this.U, sb, "onTertiaryFixedVariant=");
        sb.append((Object) co.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
